services:
  app:
    container_name: "app-arevbond"
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - .:/app
    working_dir: /app
    command: go run ./cmd/arevbond/main.go
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8888:8080

  db:
    container_name: "blog-database"
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DBNAME}"]
      interval: 10s
      timeout: 10s
      retries: 3

  migrate:
    container_name: "goose-migrator"
    build:
      dockerfile: Dockerfile.migrations
    volumes:
      - ./migrations:/migrations
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["postgres", "${DATABASE_URL}", "up"]
    depends_on:
      db:
        condition: service_healthy
