services:
  app:
    container_name: "app-arevbond"
    image: blessyo7/arevbond-blog
    working_dir: /app
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    volumes:
      - ./images:/app/images
    restart: unless-stopped
    env_file:
      - .env
        
  db:
    container_name: "blog-database"
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_DB: ${PG_USERNAME}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME} -d ${PG_DBNAME}"]
      interval: 10s
      timeout: 10s
      retries: 3

  migrate:
    container_name: "goose-migrator"
    build:
      dockerfile: Dockerfile.migrations
    volumes:
      - ./migrations:/migrations
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: ["postgres", "${DATABASE_URL}", "up"]
    depends_on:
      db:
        condition: service_healthy
    restart: no

volumes:
  postgres_data: