name: Deploy to VPS

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code from repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run tests
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Get code from repository
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: blessyo7/arevbond-blog:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:  
      - name: Get code from repository
        uses: actions/checkout@v4

      - name: Copy migrations to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "migrations/*"
          target: "/home/arevbond/arevbond-blog/"

      - name: Restart app on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/arevbond/arevbond-blog
            docker compose pull app
            sudo systemctl restart arevbond-blog.service